#Purpose - code should be automatically deplyed on ec2 instance when we push anything on main branch 
name: GitHub Actions For CICD with AWS EC2 | GitHub workflows | CICD

on:
  push:
    branches:
        - main   #Triggers this workflows on every commits or push to main branch
                 # there are 2 jobs, build and deploy, deploy job gets treiggered only when build job is run and build is available
jobs:
  build:                    #1st Build job, checks build is getting generated or not, if generated then code will be deployed on server otherwise no
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use node js
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm install
          npm run build

        env: 
          CI: true   


  depoly:
    needs: [build] #Depends on above build job, if build is generated then this job will executed or not
    runs-on: ubuntu-latest

    steps:
     - name: SSH deploy
       uses: appleboy/ssh-action@master #applyboy plugins lets us connect to server using ssh and runs multiple cmd on server
       with:
          host: ${{ secrets.HOST }}
          username:  ${{ secrets.USER }}
          key:  ${{ secrets.KEY }}
          port:  ${{ secrets.PORT }}   #nvm, can use multiple node version
          script: |
              curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash 
              . ~/.nvm/nvm.sh  
  
               nvm instal 14
               npm install -g pm2
               cd ~/CICD
               git pull origin main
               npm install
               npm run build
               pm2 restart api
            



